name: Analyzer tests

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'editors/code/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'editors/code/**'
      - '**/*.md'

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            cc: -cc clang
          - os: ubuntu-latest
            cc: -cc gcc
          - os: windows-latest
            cc: -cc gcc
      fail-fast: false

    name: Analyzer tests on ${{ matrix.os }} with ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Checkout v-analyzer
        uses: actions/checkout@v4
        with:
          path: v-analyzer
          submodules: true

      - name: Run tests
        run: |
          cd v-analyzer/tests
          v ${{ matrix.cc }} run .

      - name: Run other V tests
        run: |
          cd v-analyzer
          v ${{ matrix.cc }} test .
