name: Analyzer tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
          - os: macos-latest

    name: Analyzer tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Checkout v-analyzer
        uses: actions/checkout@v3
        with:
          path: v-analyzer

      - name: Install dependencies
        run: |
          cd v-analyzer
          v install

      - name: Run tests
        run: |
          cd v-analyzer/tests
          v run .

      - name: Run other V tests
        run: |
          cd v-analyzer
          v test .
