name: Analyzer tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-20.04
            cc: -cc tcc
          - os: windows-latest
            cc: -cc gcc

    name: Analyzer tests on ${{ matrix.os }} with ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        if: matrix.cc == '-cc gcc'
        with:
          platform: x64

      - name: Checkout v-analyzer
        uses: actions/checkout@v3
        with:
          path: v-analyzer

      - name: Install dependencies
        run: |
          cd v-analyzer
          v install

      - name: Run tests
        run: |
          cd v-analyzer/tests
          v ${{ matrix.cc }} run .

      - name: Run other V tests
        run: |
          cd v-analyzer
          v ${{ matrix.cc }} test .
