name: Build CI

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
      fail-fast: false

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Checkout v-analyzer
        uses: actions/checkout@v4
        with:
          path: v-analyzer

      - name: Install dependencies
        run: |
          cd v-analyzer
          v install

      - name: Build Debug
        run: |
          cd v-analyzer
          v build.vsh

      - name: Check if the build is successful
        run: |
          cd v-analyzer
          ./bin/v-analyzer --version

      - name: Build Release
        run: |
          cd v-analyzer
          v build.vsh release

      - name: Check if the build is successful
        run: |
          cd v-analyzer
          ./bin/v-analyzer --version
