name: Build CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
          - os: macos-latest
          - os: windows-latest

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Checkout v-analyzer
        uses: actions/checkout@v3
        with:
          path: v-analyzer

      - name: Install dependencies
        run: |
          cd v-analyzer
          v install

      - name: Build Debug
        run: |
          cd v-analyzer
          v build.vsh

      - name: Check if the build is successful
        run: |
          cd v-analyzer
          ./bin/v-analyzer --version

      - name: Build Release
        run: |
          cd v-analyzer
          v build.vsh release

      - name: Check if the build is successful
        run: |
          cd v-analyzer
          ./bin/v-analyzer --version
