name: Build CI

on:
  push:
    paths-ignore:
      - '.github/**'
      - '**/test/**'
      - '**/tests/**'
      - '**/*.md'
      - '**/test_*.v'
      - '**/*_test.v'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '**/test/**'
      - '**/tests/**'
      - '**/*.md'
      - '**/test_*.v'
      - '**/*_test.v'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        name: [ Debug, Dev, Release ]
        include:
          - name: Debug
            mode: debug
          - name: Dev
            mode: dev
          - name: Release
            mode: release
      fail-fast: false

    name: Build on ${{ matrix.os }} (${{ matrix.name }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install V
        id: install-v
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Checkout v-analyzer
        uses: actions/checkout@v4
        with:
          path: v-analyzer
          submodules: true

      - name: Build ${{ matrix.name }}
        run: |
          cd v-analyzer
          v run build.vsh ${{ matrix.mode }}

      - name: Check if the build is successful
        run: |
          cd v-analyzer
          ./bin/v-analyzer --version
