name: VS Code extension tests

on:
  push:
    paths:
      - 'editors/code/**'
  pull_request:
    paths:
      - 'editors/code/**'

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    name: Test VS Code Extension on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout v-analyzer
        uses: actions/checkout@v4
        with:
          path: v-analyzer

      - name: Install dependencies
        run: |
          cd v-analyzer/editors/code
          npm update

      - name: Run tests
        run: |
          cd v-analyzer/editors/code
          npm run test
